### ISSUE TITLE
result on tnt dataset

### ISSUE THREAD

**Issue by StellarCheng** [dvlab-research/Ref-NPR#3] opened 2023-03-29 04:05 UTC
Congratulations on Your excellent work, but I find the result on tnt dataset is bad. The image cannot reconstruct well in the first stage. Could you please check the result.

**Comment by JulianJuaner** [comment] 2023-03-29 05:47
Hi, thank you for your feedback. For the Ref-NPR, we encourage people to use multi-reference to enhance the result.
Please give us more details about your experiment so we can try to reproduce it. In addition, do you mean the result after training the PhotoRealistic part is not good?

**Comment by JulianJuaner** [comment] 2023-04-03 05:01
I will temporally close this issue. We recommend you follow the instructions of [Plenoxels](https://github.com/sxyu/svox2) to get reliable photorealistic results in step 2. We have tested the current code in scenes "Playground," "Family," and "Truck" and cannot reproduce your problem. You are welcome to reopen it if you are facing the same problem.

**Closed by JulianJuaner** 2023-04-03 05:01 UTC
