### ISSUE TITLE
the size of controlnet

### ISSUE THREAD

**Issue by jianglh-WHU** [dvlab-research/Ref-NPR#4] opened 2023-04-03 03:02 UTC
hi~thanks for your excellent work🤣
I also use controlnet to generate the truck in snow, but unfortunately, I can't use refnpr to get satisfactory results.
I want to know if the problem is that controlnet generates images that are integer multiples of **64 in length and width**, and then resizing them to the same size as the original image results in this error.
I would also like to ask you how to use controlnet to get an image of the same size as the reference image.

![style_image_0_tnt](https://user-images.githubusercontent.com/71580859/229400828-967a7e65-ad80-4a8a-81b7-928b505beca5.png)

![truck_0132](https://user-images.githubusercontent.com/71580859/229400815-380c22d9-ae45-4413-a51c-b3d507a3992d.png)

**Comment by jianglh-WHU** [comment] 2023-04-03 03:48
I also want to know how can you get multi-consistent images🤔

**Comment by JulianJuaner** [comment] 2023-04-03 04:06
Hi, thank you for your feedback!
From your given result, the results degradation is not caused by the alignment of the style image as we resize the image in the code before training the NPR field.
Here are some possible factors:
1. Ref-NPR is not professional in generating Photo-Realistic images, as it uses high-level features as the supervision.
2. As stated in the paper, in the TNT dataset, we recommend using multi-reference to boost the results. 
There are two ways to generate multi-consistent images:
- You can iteratively get new style images. After getting results using a single reference, you can select some images as the new reference image and feed them into stylization tools (like ControlNet). To avoid overlap, the simplest way is to choose sparse views in the training set. An accurate multi-frame consistency only has a little influence on our experiments.
- If you are using ControlNet, you can use some tools in stable-diffusion webui to make your result visually consistent [here](https://xanthius.itch.io/multi-frame-rendering-for-stablediffusion).

You can also try to enhance the result case-by-case: for example, change to a larger training schedule, use the image-set colorization function in ARF to get better colorization results (useful in cases with simple colors like the "truck in the snow"), etc.
Thank you again for your feedback and discussion!

**Comment by JulianJuaner** [comment] 2023-04-07 07:28
I will temporally close this issue. You are welcome to reopen it if you have any problems.

**Closed by JulianJuaner** 2023-04-07 07:28 UTC
